#!/usr/bin/env bash
# This is the maintainence launcher for the snap, make necessary runtime
# environment changes to make the snap work here.  You may also insert
# security confinement/deprecation/obsoletion notice of the snap here.
#
# Copyright 2025 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: MIT

set \
    -o errexit \
    -o errtrace \
    -o nounset

#export IMPORTANT_ENVIRONMENT_VARIABLE=value

# Finally run the next part of the command chain
exec "${@}"
